### ISSUE TITLE
IG paginating latitude of qty 138 results, renders blank map.

### ISSUE THREAD

**Issue by mojavemaps** [cfree/wp-karten#11]
Hi Craig, changed the max to 30 - still no map. Thanks, K

**Comment by cfree** [comment]
Thanks for reporting, @mojavemaps - I'll take a look

**Comment by wfgjk** [comment]
Hi Craig, I'm having the same issue changing the max and I'm still getting an issue.  http://theworldwalk.com

**Comment by cfree** [comment]
@wfgjk I found some documentation on [pagination](https://instagram.com/developer/endpoints/#pagination) of the API. I'm planning to do some testing around it this weekend.

**Comment by cfree** [comment]
@mojavemaps Hopefully resolving the pagination issue will resolve the issue you are having. Please report any JavaScript/console or PHP log errors.

**Comment by cfree** [comment]
@mojavemaps @wfgjk There are some disappointing aspects of the Instagram API that restrict me from doing much here. I've documented everything [here](http://craigfreeman.net/blog/2015/07/karten-1-1-1/). I have made some updates allowing you to search for hashtags without setting a user, but there are limitations. You could try making several maps based on date ranges to get around this.
